### PR TITLE
Archlinux fixes + minor improvements

### PR DESCRIPTION
**Pull request by libcrack**
- Added UTF-8 headerq
- Renamed utils.py to peda_utils.py due to Archlinux conflicts (unable to use gdb)
- Set 0x00 as default badchar, disabled default autosave and enabled extended info on command errors
- Added documentation generated with epydoc

### CODE REVIEW

**Comment by anthraxx** [comment]
@borjiviri can you explain what is causing the conflict for you, because it seems to work just fine. If you still experience the problem, please start gdb without peda and issue the following commands to get the file in charge:

    > gdb -nh
    (gdb)  python
    import utils
    print(utils)
    end

PS: I'm also not quite sure if "disabling autosave" is what upstream wants to have, my 2 cents: :-1:

**Comment by borjiviri** [comment]
Hi!

Well, I made those changes time ago, I don't remember why peda was not working on my Arch, but I do remember that I had to modify the imports cause the where implemented in a non standard way. Maybe a good idea would be to adapt peda and produce a dist-tool compatible package to distribute it easily via pip.

**Comment by anthraxx** [comment]
@borjiviri yeah, I remember there was something at some point... but i did some research now and can't find any conflicts anymore... still not 100% sure what introduced that conflicting back then, but nowadays there seems to be no globally shipped utils.py without sub-package... so my current guess is that it is obsolete now.

**Comment by anthraxx** [comment]
plase close this issue as the problem seems to be resolved for a long time and no new input was added (I'm using Arch :yum: )

**Comment by libcrack** [comment]
Archlinux r00lz

**Pull request closed without merging**
