### PR TITLE
Add support for Python 3 using the six library

### PR DESCRIPTION
**Pull request by tmfink**
Refer to python23-compatibility.md for details about supporting both
Python 2 and Python 3.

### CODE REVIEW

**Comment by tmfink** [comment]
Also, I set up a repo with a test (https://github.com/tmfink/peda-test).

The output looks the same as before the commit on both Python 2 and Python 3.

**Comment by longld** [comment]
This is nice! Can you help to check and fix for following commands under py3?
- pattern_offset/pattern_search
- lookup address/pointer
- snapshot save/restore
- strings / substr

**Comment by tmfink** [comment]
Will do. I'll let you know when I finish the tests.

**Comment by tmfink** [comment]
I have checked the commands under Python 3 and fixed some bugs with 78e74b6b7af848d1958eb7538b332382ecb084c0.

**Comment by longld** [comment]
Some minor commands still need to be fixed in py3, pls check:
- assemble
- cmpmem
- patch
- substr
- xormem

**Comment by tmfink** [comment]
I patched the bugs you mentioned.

**Comment by longld** [comment]
Great! Thanks for the patch.

**Pull request merged**
